/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Wed Aug 20 19:51:31 BRT 2014
 */
package org.jboss.keynote.salesforce.dto;

import org.codehaus.jackson.annotate.JsonCreator;
import org.codehaus.jackson.annotate.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist BackgroundDirection
 */
public enum BackgroundDirectionEnum {

    // TopToBottom
    TOPTOBOTTOM("TopToBottom"),
    // LeftToRight
    LEFTTORIGHT("LeftToRight"),
    // Diagonal
    DIAGONAL("Diagonal");

    final String value;

    private BackgroundDirectionEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static BackgroundDirectionEnum fromValue(String value) {
        for (BackgroundDirectionEnum e : BackgroundDirectionEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
