/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Wed Aug 20 19:51:31 BRT 2014
 */
package org.jboss.keynote.salesforce.dto;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import org.codehaus.jackson.annotate.JsonProperty;
import org.apache.camel.component.salesforce.api.dto.AbstractSObjectBase;

/**
 * Salesforce DTO for SObject CategoryData
 */
@XStreamAlias("CategoryData")
public class CategoryData extends AbstractSObjectBase {

    // CategoryNodeId
    private String CategoryNodeId;

    @JsonProperty("CategoryNodeId")
    public String getCategoryNodeId() {
        return this.CategoryNodeId;
    }

    @JsonProperty("CategoryNodeId")
    public void setCategoryNodeId(String CategoryNodeId) {
        this.CategoryNodeId = CategoryNodeId;
    }

    // RelatedSobjectId
    private String RelatedSobjectId;

    @JsonProperty("RelatedSobjectId")
    public String getRelatedSobjectId() {
        return this.RelatedSobjectId;
    }

    @JsonProperty("RelatedSobjectId")
    public void setRelatedSobjectId(String RelatedSobjectId) {
        this.RelatedSobjectId = RelatedSobjectId;
    }

}
