/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Wed Aug 20 19:51:31 BRT 2014
 */
package org.jboss.keynote.salesforce.dto;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import org.codehaus.jackson.annotate.JsonProperty;
import org.apache.camel.component.salesforce.api.dto.AbstractSObjectBase;

/**
 * Salesforce DTO for SObject ContentWorkspace
 */
@XStreamAlias("ContentWorkspace")
public class ContentWorkspace extends AbstractSObjectBase {

    // Description
    private String Description;

    @JsonProperty("Description")
    public String getDescription() {
        return this.Description;
    }

    @JsonProperty("Description")
    public void setDescription(String Description) {
        this.Description = Description;
    }

    // TagModel
    private String TagModel;

    @JsonProperty("TagModel")
    public String getTagModel() {
        return this.TagModel;
    }

    @JsonProperty("TagModel")
    public void setTagModel(String TagModel) {
        this.TagModel = TagModel;
    }

    // DefaultRecordTypeId
    private String DefaultRecordTypeId;

    @JsonProperty("DefaultRecordTypeId")
    public String getDefaultRecordTypeId() {
        return this.DefaultRecordTypeId;
    }

    @JsonProperty("DefaultRecordTypeId")
    public void setDefaultRecordTypeId(String DefaultRecordTypeId) {
        this.DefaultRecordTypeId = DefaultRecordTypeId;
    }

    // IsRestrictContentTypes
    private Boolean IsRestrictContentTypes;

    @JsonProperty("IsRestrictContentTypes")
    public Boolean getIsRestrictContentTypes() {
        return this.IsRestrictContentTypes;
    }

    @JsonProperty("IsRestrictContentTypes")
    public void setIsRestrictContentTypes(Boolean IsRestrictContentTypes) {
        this.IsRestrictContentTypes = IsRestrictContentTypes;
    }

    // IsRestrictLinkedContentTypes
    private Boolean IsRestrictLinkedContentTypes;

    @JsonProperty("IsRestrictLinkedContentTypes")
    public Boolean getIsRestrictLinkedContentTypes() {
        return this.IsRestrictLinkedContentTypes;
    }

    @JsonProperty("IsRestrictLinkedContentTypes")
    public void setIsRestrictLinkedContentTypes(Boolean IsRestrictLinkedContentTypes) {
        this.IsRestrictLinkedContentTypes = IsRestrictLinkedContentTypes;
    }

}
