/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Wed Aug 20 19:51:31 BRT 2014
 */
package org.jboss.keynote.salesforce.dto;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamConverter;
import org.codehaus.jackson.annotate.JsonProperty;
import org.apache.camel.component.salesforce.api.PicklistEnumConverter;
import org.apache.camel.component.salesforce.api.dto.AbstractSObjectBase;

/**
 * Salesforce DTO for SObject ContentDocumentLink
 */
@XStreamAlias("ContentDocumentLink")
public class ContentDocumentLink extends AbstractSObjectBase {

    // LinkedEntityId
    private String LinkedEntityId;

    @JsonProperty("LinkedEntityId")
    public String getLinkedEntityId() {
        return this.LinkedEntityId;
    }

    @JsonProperty("LinkedEntityId")
    public void setLinkedEntityId(String LinkedEntityId) {
        this.LinkedEntityId = LinkedEntityId;
    }

    // ContentDocumentId
    private String ContentDocumentId;

    @JsonProperty("ContentDocumentId")
    public String getContentDocumentId() {
        return this.ContentDocumentId;
    }

    @JsonProperty("ContentDocumentId")
    public void setContentDocumentId(String ContentDocumentId) {
        this.ContentDocumentId = ContentDocumentId;
    }

    // ShareType
    @XStreamConverter(PicklistEnumConverter.class)
    private ShareTypeEnum ShareType;

    @JsonProperty("ShareType")
    public ShareTypeEnum getShareType() {
        return this.ShareType;
    }

    @JsonProperty("ShareType")
    public void setShareType(ShareTypeEnum ShareType) {
        this.ShareType = ShareType;
    }

}
