/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Wed Aug 20 19:51:31 BRT 2014
 */
package org.jboss.keynote.salesforce.dto;

import org.codehaus.jackson.annotate.JsonCreator;
import org.codehaus.jackson.annotate.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist Field
 */
public enum FieldEnum {

    // ActivatedBy
    ACTIVATEDBY("ActivatedBy"),
    // ActivatedDate
    ACTIVATEDDATE("ActivatedDate"),
    // BillingAddress
    BILLINGADDRESS("BillingAddress"),
    // BillingCity
    BILLINGCITY("BillingCity"),
    // BillingCountry
    BILLINGCOUNTRY("BillingCountry"),
    // BillingLatitude
    BILLINGLATITUDE("BillingLatitude"),
    // BillingLongitude
    BILLINGLONGITUDE("BillingLongitude"),
    // BillingPostalCode
    BILLINGPOSTALCODE("BillingPostalCode"),
    // BillingState
    BILLINGSTATE("BillingState"),
    // BillingStreet
    BILLINGSTREET("BillingStreet"),
    // BillToContact
    BILLTOCONTACT("BillToContact"),
    // CompanyAuthorizedBy
    COMPANYAUTHORIZEDBY("CompanyAuthorizedBy"),
    // CompanyAuthorizedDate
    COMPANYAUTHORIZEDDATE("CompanyAuthorizedDate"),
    // created
    CREATED("created"),
    // CustomerAuthorizedBy
    CUSTOMERAUTHORIZEDBY("CustomerAuthorizedBy"),
    // CustomerAuthorizedDate
    CUSTOMERAUTHORIZEDDATE("CustomerAuthorizedDate"),
    // Description
    DESCRIPTION("Description"),
    // EffectiveDate
    EFFECTIVEDATE("EffectiveDate"),
    // EndDate
    ENDDATE("EndDate"),
    // feedEvent
    FEEDEVENT("feedEvent"),
    // Name
    NAME("Name"),
    // Opportunity
    OPPORTUNITY("Opportunity"),
    // orderActivated
    ORDERACTIVATED("orderActivated"),
    // orderApproved
    ORDERAPPROVED("orderApproved"),
    // orderCancelled
    ORDERCANCELLED("orderCancelled"),
    // orderDeactivated
    ORDERDEACTIVATED("orderDeactivated"),
    // orderExpired
    ORDEREXPIRED("orderExpired"),
    // OrderReferenceNumber
    ORDERREFERENCENUMBER("OrderReferenceNumber"),
    // orderSubmitted
    ORDERSUBMITTED("orderSubmitted"),
    // ownerAccepted
    OWNERACCEPTED("ownerAccepted"),
    // ownerAssignment
    OWNERASSIGNMENT("ownerAssignment"),
    // PoDate
    PODATE("PoDate"),
    // PoNumber
    PONUMBER("PoNumber"),
    // Pricebook2
    PRICEBOOK2("Pricebook2"),
    // locked
    LOCKED("locked"),
    // unlocked
    UNLOCKED("unlocked"),
    // ShippingAddress
    SHIPPINGADDRESS("ShippingAddress"),
    // ShippingCity
    SHIPPINGCITY("ShippingCity"),
    // ShippingCountry
    SHIPPINGCOUNTRY("ShippingCountry"),
    // ShippingLatitude
    SHIPPINGLATITUDE("ShippingLatitude"),
    // ShippingLongitude
    SHIPPINGLONGITUDE("ShippingLongitude"),
    // ShippingPostalCode
    SHIPPINGPOSTALCODE("ShippingPostalCode"),
    // ShippingState
    SHIPPINGSTATE("ShippingState"),
    // ShippingStreet
    SHIPPINGSTREET("ShippingStreet"),
    // ShipToContact
    SHIPTOCONTACT("ShipToContact"),
    // Status
    STATUS("Status"),
    // StatusCode
    STATUSCODE("StatusCode"),
    // Type
    TYPE("Type");

    final String value;

    private FieldEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static FieldEnum fromValue(String value) {
        for (FieldEnum e : FieldEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
