/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Wed Aug 20 19:51:31 BRT 2014
 */
package org.jboss.keynote.salesforce.dto;

import org.codehaus.jackson.annotate.JsonCreator;
import org.codehaus.jackson.annotate.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist GeoCodeAccuracy
 */
public enum GeoCodeAccuracyEnum {

    // D
    D("D"),
    // S
    S("S"),
    // B
    B("B"),
    // T
    T("T"),
    // M
    M("M"),
    // Z
    Z("Z"),
    // 0
    _0("0"),
    // C
    C("C"),
    // N
    N("N"),
    // I
    I("I"),
    // P
    P("P");

    final String value;

    private GeoCodeAccuracyEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static GeoCodeAccuracyEnum fromValue(String value) {
        for (GeoCodeAccuracyEnum e : GeoCodeAccuracyEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
