/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Wed Aug 20 19:51:31 BRT 2014
 */
package org.jboss.keynote.salesforce.dto;

import org.codehaus.jackson.annotate.JsonCreator;
import org.codehaus.jackson.annotate.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist JobType
 */
public enum JobTypeEnum {

    // Future
    FUTURE("Future"),
    // SharingRecalculation
    SHARINGRECALCULATION("SharingRecalculation"),
    // ScheduledApex
    SCHEDULEDAPEX("ScheduledApex"),
    // BatchApex
    BATCHAPEX("BatchApex"),
    // BatchApexWorker
    BATCHAPEXWORKER("BatchApexWorker"),
    // TestRequest
    TESTREQUEST("TestRequest"),
    // TestWorker
    TESTWORKER("TestWorker"),
    // ApexToken
    APEXTOKEN("ApexToken");

    final String value;

    private JobTypeEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static JobTypeEnum fromValue(String value) {
        for (JobTypeEnum e : JobTypeEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
