/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Wed Aug 20 19:51:31 BRT 2014
 */
package org.jboss.keynote.salesforce.dto;

import org.codehaus.jackson.annotate.JsonCreator;
import org.codehaus.jackson.annotate.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist MarketingPreScreen
 */
public enum MarketingPreScreenEnum {

    // L
    L("L"),
    // M
    M("M"),
    // H
    H("H");

    final String value;

    private MarketingPreScreenEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static MarketingPreScreenEnum fromValue(String value) {
        for (MarketingPreScreenEnum e : MarketingPreScreenEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
