/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Wed Aug 20 19:51:31 BRT 2014
 */
package org.jboss.keynote.salesforce.dto;

import org.codehaus.jackson.annotate.JsonCreator;
import org.codehaus.jackson.annotate.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist ProviderType
 */
public enum ProviderTypeEnum {

    // Facebook
    FACEBOOK("Facebook"),
    // Janrain
    JANRAIN("Janrain"),
    // Salesforce
    SALESFORCE("Salesforce"),
    // OpenIdConnect
    OPENIDCONNECT("OpenIdConnect"),
    // MicrosoftACS
    MICROSOFTACS("MicrosoftACS");

    final String value;

    private ProviderTypeEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static ProviderTypeEnum fromValue(String value) {
        for (ProviderTypeEnum e : ProviderTypeEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
