/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Wed Aug 20 19:51:31 BRT 2014
 */
package org.jboss.keynote.salesforce.dto;

import org.codehaus.jackson.annotate.JsonCreator;
import org.codehaus.jackson.annotate.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist StatusCode
 */
public enum StatusCodeEnum {

    // Draft
    DRAFT("Draft"),
    // InApproval
    INAPPROVAL("InApproval"),
    // Activated
    ACTIVATED("Activated"),
    // Terminated
    TERMINATED("Terminated"),
    // Expired
    EXPIRED("Expired");

    final String value;

    private StatusCodeEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static StatusCodeEnum fromValue(String value) {
        for (StatusCodeEnum e : StatusCodeEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
