/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Wed Aug 20 19:51:31 BRT 2014
 */
package org.jboss.keynote.salesforce.dto;

import org.codehaus.jackson.annotate.JsonCreator;
import org.codehaus.jackson.annotate.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist TemplateStyle
 */
public enum TemplateStyleEnum {

    // none
    NONE("none"),
    // freeForm
    FREEFORM("freeForm"),
    // formalLetter
    FORMALLETTER("formalLetter"),
    // promotionRight
    PROMOTIONRIGHT("promotionRight"),
    // promotionLeft
    PROMOTIONLEFT("promotionLeft"),
    // newsletter
    NEWSLETTER("newsletter"),
    // products
    PRODUCTS("products");

    final String value;

    private TemplateStyleEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static TemplateStyleEnum fromValue(String value) {
        for (TemplateStyleEnum e : TemplateStyleEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
