/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Wed Aug 20 19:51:31 BRT 2014
 */
package org.jboss.keynote.salesforce.dto;

import org.codehaus.jackson.annotate.JsonCreator;
import org.codehaus.jackson.annotate.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist Type
 */
public enum TypeEnum {

    // Prospect
    PROSPECT("Prospect"),
    // Customer - Direct
    CUSTOMER___DIRECT("Customer - Direct"),
    // Customer - Channel
    CUSTOMER___CHANNEL("Customer - Channel"),
    // Channel Partner / Reseller
    CHANNEL_PARTNER___RESELLER("Channel Partner / Reseller"),
    // Installation Partner
    INSTALLATION_PARTNER("Installation Partner"),
    // Technology Partner
    TECHNOLOGY_PARTNER("Technology Partner"),
    // Other
    OTHER("Other");

    final String value;

    private TypeEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
        for (TypeEnum e : TypeEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
