/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Wed Aug 20 19:51:31 BRT 2014
 */
package org.jboss.keynote.salesforce.dto;

import org.codehaus.jackson.annotate.JsonCreator;
import org.codehaus.jackson.annotate.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist UserType
 */
public enum UserTypeEnum {

    // Standard
    STANDARD("Standard"),
    // PowerPartner
    POWERPARTNER("PowerPartner"),
    // PowerCustomerSuccess
    POWERCUSTOMERSUCCESS("PowerCustomerSuccess"),
    // CustomerSuccess
    CUSTOMERSUCCESS("CustomerSuccess"),
    // Guest
    GUEST("Guest"),
    // CspLitePortal
    CSPLITEPORTAL("CspLitePortal"),
    // CsnOnly
    CSNONLY("CsnOnly"),
    // SelfService
    SELFSERVICE("SelfService");

    final String value;

    private UserTypeEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static UserTypeEnum fromValue(String value) {
        for (UserTypeEnum e : UserTypeEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
