/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Wed Aug 20 19:51:31 BRT 2014
 */
package org.jboss.keynote.salesforce.dto;

import org.codehaus.jackson.annotate.JsonCreator;
import org.codehaus.jackson.annotate.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist YearType
 */
public enum YearTypeEnum {

    // Standard
    STANDARD("Standard"),
    // Custom
    CUSTOM("Custom"),
    // Placeholder
    PLACEHOLDER("Placeholder");

    final String value;

    private YearTypeEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static YearTypeEnum fromValue(String value) {
        for (YearTypeEnum e : YearTypeEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
